### ISSUE TITLE
function

### ISSUE THREAD

**Issue by mardon86** [sparkslabs/pyxie#1]
Hi, @sparkslabs  Pyxie is an awesome project. Is it actively developed ? when defining function will be implemented ?

**Comment by sparkslabs** [comment]
Hi!

Thanks for the kind words. Yes, Pyxie is actively developed. It's stalled a bit recently due to other commitments, but it is actively developed - though only in my "spare" time :)

My current focus is to make it possible to develop simple programs targetting this device by DAGU -

https://robosavvy.com/store/dagu-playful-puppy.html

There's several things I need for that to work - one is to make the arduino profile more fleshed out to include control of servos and similar. For that to work, I need object creation working (from libraries) and also method calls. The latter has been taking a little longer than expected, which is really the reason for delay. (needs slight grammar rework)

Once that's working, then function definitions will be on the list. Being realistic that's probably **within a month or so?** (Dependent on other things in life)

In particular, from my notes the arduino profile needs the following implementing first:
- Arduino profile:
  - Need to support the following things at minimum:
  - Constants:
  - OUTPUT, INPUT (pinModes)
  - HIGH, LOW (general pin values)
  - functions/etc
  - digitalWrite
  - delayMicroseconds
  - pinMode
  - analogRead
  - millis
  - Hardware devices/libraries etc
  - Servo
  - IOToy (maybe)
  - prototype microbit (maybe)

From a language perspective the high level priorities are _at the moment_:
- def - function definitions - and therefore implementation of scope
- What happens with mixed types in expressions
- Modulo operator support
- import statements
- yield - generator definitions
- class - class definitions
- object usage - method access, and attribute access

Hopefully that's useful.

**Comment by sparkslabs** [comment]
0.0.18 release pushed FWIW.
