### ISSUE TITLE
Make this repo more visible

### ISSUE THREAD

**Issue by butla** [sparkslabs/pyxie#23]
Hey! I've just stumbled on your project wondering if I could fit micropython on an Atmega8 (I can't). It looks very nice!
Anyway, I've spent some time looking for the source code. I guess the link to GitHub could be better advertised. For example, it could be the "homepage URL" on PyPI (and readme could point to http://www.sparkslabs.com/pyxie/ then)

**Comment by sparkslabs** [comment]
Interesting suggestion.

I'll take it on board - and make a change on the next update. I'll probably actually create a pointer on the homepage that points here, but it's a good suggestion.

(Been a bit time starved recently!)

I'll close this issue when I make the change.

**Comment by sparkslabs** [comment]
Any issue I haven't had a chance to do in 6 months means I'm time starved, and leaving this open leaves expectations which aren't realistic. If you want to offer a specific change via a pull request, please do so.
That said, this is a nice idea, but can't guarantee when this might happen - so I'll add it to my trello list instead of leaving this open.

**Comment by butla** [comment]
@sparkslabs I think of issues as public TODOs. Maybe if you leave it open someone who's using your project will take it upon themselves? Especially since you don't have that many open issues. But it's your project, so do what you want :)

Anyway, I'm also pretty time-starved, and I also have an ever-expanding (hope that'll stop at one point) TODO list, but mine's on Wunderlist :)

**Comment by sparkslabs** [comment]
True - I get your point.  I've added it onto the trello list though, since it is a good thing.

FWIW, in my case, I snapshot the card names from my pyxie trello into the website here:
http://www.sparkslabs.com/pyxie/dev-status.html

You'll see "make this repo more visible" was added to the section "Release Backlog: Features", which is generally "stuff I'm aiming towards for the next release, whenever that is", rather than the unprioritised list.

Regarding getting pull requests for help, that'd be nice, but I also probably need to document how people can do that in the case of the pyxie website. The way it's built is in this repo, but that's not documented. But then doing *that* s the section "Release Backlog: Tasks".

Anyway, many thanks for the suggestion it was welcome, and at some point I will do it :)
